; gcodes which are specific for Cura in Marlin flavor
; (same gcode commands may also be created by other generators, but are not generic)

; gdecoder detects the gcode generator used by generator specific comments in the file
; the following lines are needed to detect this file was generated by Cura/Marlin. Hopefully obvious, this is a synthetic example and was NOT generated by Cura!
;Generated with Cura_SteamEngine 5.5.0
;FLAVOR:Marlin

M204 P2500 R2500 T2500
M204 S1000
M205 X8.00 Y8.00 Z0.40 E8.00
M205 S0 T0
