; gcodes which are specific for Prusaslicer
; (same gcode commands may also be created by other generators, but are not generic)

; gdecoder detects the gcode generator used by generator specific comments in the file
; the following line is needed to detect this file was generated by Prusaslicer. Hopefully obvious, this is a synthetic example and was NOT generated by Prusaslicer!
; generated by PrusaSlicer

M203 X250 Y250 Z8 E80
M204 P2500 R2500 T2500
M204 S1000
M205 X8.00 Y8.00 Z0.40 E8.00
M205 S0 T0
M221 S95
M862.1 P0.4
M862.3 P "MK3S"
M900 K0
M900 K0.06
M900 K30
M907 E430
