; gcodes which are specific for Sli3er
; (same gcode commands may also be created by other generators, but are not generic)

; gdecoder detects the gcode generator used by generator specific comments in the file
; the following line is needed to detect this file was generated by Slic3r. Hopefully obvious, this is a synthetic example and was NOT generated by Slic3r!
; generated by Slic3r

M204 P2500 R2500 T2500
M204 S1000
M221 S95
M900 K0
M900 K0.06
M900 K30
